# Usa l'immagine coady/pylucene come base
FROM coady/pylucene:latest

# Imposta la directory di lavoro nel container
WORKDIR /workspace

# Copia tutti i file del progetto nella directory di lavoro del container
COPY . /workspace

# Comando di default per accedere al container
CMD ["bash"]